# Copyright (C) 2023 Kynn/Cherryblue
#   This file is part of Secured-front (https://github.com/Cherryblue/secured-front).
#   Secured-front is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#   Secured-front is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License along with Secured-front. If not, see <https://www.gnu.org/licenses/>. 
#
#
# This file is based on the default NGINX configuration file. For more options, I encourage you to check on https://nginx.org/en/

worker_processes                auto; # it will be determinate automatically by the number of core
worker_rlimit_nofile            100;
error_log                       /var/log/nginx/error.log warn;
pid                             /var/run/nginx/nginx.pid;

events {
    worker_connections          100;
}

http {
    charset                     utf-8;
    client_max_body_size        512M;
    include                     mime.types;
    default_type                application/octet-stream;
    access_log                  off;
    server_tokens               off;
    sendfile                    on;
    access_log                  /var/log/nginx/access.log;
    keepalive_timeout           5;
    tcp_nodelay                 off;
    server_name_in_redirect     off;
    types_hash_max_size         2048;
    gzip                        off;

    server {
       listen 54321;
       server_name  _;

       # FOR CERTIFICATES
       location ^~ /.well-known/acme-challenge {
           alias /var/www/dehydrated;
           break;
       }
    }
}
